# Generated by Django 3.2 on 2022-02-15 18:17
import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('photo', models.ImageField(blank=True, max_length=256, null=True,
                                            upload_to=catalog.models.ProductImage.get_file_path)),
                ('created_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_productimage_created_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='images', to='catalog.product')),
                ('updated_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_productimage_updated_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
