# Generated by Django 3.2 on 2022-02-04 15:15

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=255, verbose_name='category')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to='categories/%Y/%m/%d', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_category_created_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Created By')),
                ('parent_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                 to='catalog.category', verbose_name='parent_category')),
                ('updated_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_category_updated_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='manufacturers/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_manufacturer_created_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Created By')),
                ('updated_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_manufacturer_updated_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=20000, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('sku', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, help_text='in percent', null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                               related_name='products', to='catalog.category')),
                ('created_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_product_created_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Created By')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                   related_name='products', to='catalog.manufacturer')),
                ('updated_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_product_updated_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('photo', models.ImageField(blank=True, max_length=256, null=True,
                                            upload_to=catalog.models.ProductImage.get_file_path)),
                ('created_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_productimage_created_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='images', to='catalog.product')),
                ('updated_by',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='catalog_productimage_updated_by', to=settings.AUTH_USER_MODEL,
                                   verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
