# Generated by Django 3.2 on 2022-01-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parent_id',
            new_name='parent_cat',
        ),
    ]
