# Generated by Django 3.2 on 2022-02-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='big_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/big/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to='products/original/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='small_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/small/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='ProductImageRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='products', through='catalog.ProductImageRelated', to='catalog.ProductImage'),
        ),
    ]
