# Generated by Django 3.2 on 2022-01-29 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220129_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_manufacturer', to='catalog.manufacturer'),
        ),
    ]
